### ISSUE TITLE
华为P10 真机运行example报错

### ISSUE THREAD

**Issue by Unrivaled2** [aliyoge/flutter_file_preview#1]
Launching lib\main.dart on VTR AL00 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install D:\ljt\flutter_file_preview-master\example\build\app\outputs\apk\app.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
Error launching application on VTR AL00.

**Comment by aliyoge** [comment]
@Unrivaled2 看一下新版本。
