### ISSUE TITLE
为什么点击打开文件没反应呢？

### ISSUE THREAD

**Issue by BefightingMan** [aliyoge/flutter_file_preview#2]
RaisedButton(
                color: Theme.of(context).primaryColor,
                textColor: Colors.white,
                child: Text('打开word文档'),
                onPressed: (){
                  FilePreview.openFile("http://cdn.dev.jiazhangkj.com/miniprofile/20200417/7DDE1F987D6FFEA31180A3F444403DFB.docx");
                },
              ),

**Comment by aliyoge** [comment]
@BefightingMan 应该是文件链接有问题，看一下新版本。
