### ISSUE TITLE
使用模拟器打开文件时出现异常

### ISSUE THREAD

**Issue by pipiaha** [aliyoge/flutter_file_preview#5]
Unhandled Exception: PlatformException(error, Unable to find explicit activity class {[我的工程包路径]/zzaning.com.filepreview.FileDisplayActivity}; have you declared this activity in your AndroidManifest.xml?, null)
E/flutter ( 4145): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 4145): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter ( 4145): <asynchronous suspension>
E/flutter ( 4145): #2      FilePreview.openFile (package:file_preview/file_preview.dart:11:42)
E/flutter ( 4145): #3      TrainHomeScreenWidget._buildExamArea.<anonymous closure> (package:ais/train/train_home.dart:278:39)
E/flutter ( 4145): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter ( 4145): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter ( 4145): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 4145): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter ( 4145): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter ( 4145): #9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
E/flutter ( 4145): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 4145): #11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter ( 4145): #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 4145): #13     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 4145): #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 4145): #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 4145): #16     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter ( 4145): #17     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 4145): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 4145): #19     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter ( 4145): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter ( 4145):

**Comment by aliyoge** [comment]
@pipiaha 请尝试一下新版本

**Comment by burakcbdn** [comment]
Same issue
